on:
  - push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: hata6502/no-broken-dependency-action@main
        with:
          default-branch: master
