on:
  - push

jobs:
  check-dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # Latest release: hata6502/no-broken-dependency-action@v3
      - uses: hata6502/no-broken-dependency-action@main
        with:
          default-branch: master
